import env from '../.env.json';
export const FIREBASE_KEY = env.FIREBASE_KEY;
export const FIREBASE_DOMAIN = env.FIREBASE_DOMAIN;
export const FIREBASE_PROJECT_ID = env.FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET = env.FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID = env.FIREBASE_MESSAGING_SENDER_ID;
export const FIREBASE_APP_ID = env.FIREBASE_APP_ID;
